language: node_js

node_js: 
  - "5.1"
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - bower install

script: 
  - npm install
  #- npm test
  - npm run unit-test
